import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

import { Toaster } from "sonner";
import { FolderProvider } from "@/contexts/folder-context";
import { SharedAppSidebar } from "@/components/shared-app-sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { shareToken: string };
}>) {
  const { shareToken } = await params;
  console.log(shareToken);
  return (
    <>
        <FolderProvider initialShareToken={ shareToken }>
          <SidebarProvider>        
              <SharedAppSidebar
                readOnly={true}/>
              <SidebarTrigger />
              {children}
              <Toaster richColors position="top-right"/>
          </SidebarProvider>
        </FolderProvider>
    </>
  );
}